### ISSUE TITLE
Unable to sort because of "loops of dependencies"

### ISSUE THREAD

**Issue by 035WasTaken** [rimpy-custom/RimPy#95]
Since updating to 1.4 I've been getting this error with these mods:

There are loops of dependencies in your mods list.
- ludeon.rimworld
- brrainz.harmony
- ludeon.rimworld.biotech
- ludeon.rimworld.ideology
- ludeon.rimworld.royalty

I'm not sure if this is relevant, but it mentions having multiple recursive dependencies but just lists the same 5 items in different orders. I suspect maybe the structure of the About.xml file has changed in some fundamental way in 1.4 but I haven't confirmed this and it's just a theory.

**Comment by NoShotz** [comment]
Also getting this.

**Comment by NoShotz** [comment]
Considering it is even doing this without any mods active, there is definitely something wrong
![image](https://user-images.githubusercontent.com/13302841/197305528-9c32fa70-d9d2-42d6-bc42-cc746de114f2.png)

For reference here's the 4 About.xml files from the base game and DLC's
![image](https://user-images.githubusercontent.com/13302841/197305700-493ea224-63b5-49f3-b26a-bfd3a7f630a3.png)

**Comment by NyxZoldrent** [comment]
Also getting this. Temporary work around floating around, disable biotech, sort mod list, then manually drag it right below base game/royalty/ideology

**Comment by diboxide** [comment]
> Also getting this. Temporary work around floating around, disable biotech, sort mod list, then manually drag it right below base game/royalty/ideology

thank you for this temporary workaround. that seems like it's something so simple but it slips the mind.

**Comment by Official-Husko** [comment]
same issue but with certain mods. This did not happen before the update. i also checked some of the mods and they are not dependent or even referencing each other in the about.xml file.
![image](https://user-images.githubusercontent.com/27901510/197335706-a4fe8804-570c-4ff2-a944-d0d572d460a9.png)

**Comment by Adda0** [comment]
Regarding the loop dependency between Hospitability and Prison Labor, there is a response in the comments section on [Steam Workshop page of Prison Labor](https://steamcommunity.com/sharedfiles/filedetails/?id=1899474310) from Hazzer, the author of Prison Labor:
> @ Yaoji Are you using rimpy? Rimpy has a rule created by someone (nor me or Orion) and thats why you see this warning. If you check Hospitality mod about file: [https://github.com/OrionFive/Hospitality/blob/develop/About/About.xml](https://steamcommunity.com/linkfilter/?url=https://github.com/OrionFive/Hospitality/blob/develop/About/About.xml) you can see that there is no rule about order. Using old rule with rimworld 1.3 is fine but in 1.4 my recommendation is to keep order from Prion Labor.

**Comment by samerogers** [comment]
Another temporary fix is to update your sorting rules for Harmony, Core, Royalty, and Ideology to explicitly add Biotech as dependent.

![image](https://user-images.githubusercontent.com/1059458/197351028-dafc943b-8f45-4796-a40c-63e752f7e8dd.png)

**Comment by rimpy-custom** [comment]
You should never fix loop dependencies by creating new rules! You should wait for a hotfix.

**Comment by rimpy-custom** [comment]
Update was published. Keep iy open in case issue wasn't resolved.

**Comment by 035WasTaken** [comment]
Works for my modlist now, thanks for the quick fix !

**Comment by rimpy-custom** [comment]
Thanks for the confirmation. Closing.

**Comment by Adda0** [comment]
Could we get a Linux binary for the new update, too? As of now, I cannot confirm nor refute that the additional errors mentioned above were fixed.

**Comment by Adda0** [comment]
Thanks for the Linux binary. I confirm that my loop dependencies were fixed as well.

**Comment by Norel** [comment]
I'm still having this loops of dependencies error :
![image](https://user-images.githubusercontent.com/4608761/198979112-6d53d965-43c0-442b-8230-49d222969dd2.png)
Which makes sense if we follow the modder based ruleset :
![image](https://user-images.githubusercontent.com/4608761/198979735-b2601ea3-4b9f-4b4d-a323-9124eb27852d.png)
